added MapReverse for reversing an array of maps
vatsalpatel/GoFusion pull request #7
Opened 2023-12-03 06:25 UTC by AryanSingh11

Hello, I know that you already have a reverse function for reversing any sort of array.
I was just browsing through the repo, after I came across your LinkedIn.
I have created a reverseMap function inside the Maps.go file itself. Pls let me know if you'd like me to make any changes.

Also, some more additions in .gitignore. I used Goland so some more additions were needed.
Let me know if you want me to create a separate PR for .gitignore.

2023-12-03 09:31 UTC, AryanSingh11 commented
I have created a MergeFirst also, its similar to Merge in maps.go, but
MergeFirst merges multiple maps into a single map. It's a bit different from Merge.
If duplicate keys are encountered, the value from the First map in the input order is used.

2023-12-04 11:32 UTC, vatsalpatel commented on maps.go
> +}
It is really unnecessary. A slice of maps is still a slice. Just use Reverse()

2023-12-04 11:35 UTC, vatsalpatel requested changes
Also tests are not written for added functions

2023-12-04 11:35 UTC, vatsalpatel commented on maps.go
> +}
This is unnecessary. But it is also a really bad way to do it. You can just check whether key exists or not; if key already exists in result then just continue

2023-12-04 11:35 UTC, vatsalpatel commented on maps.go
> +}
It is really unnecessary. A slice of maps is still a slice. Just use Reverse()
So remove this function altogether

2023-12-04 11:35 UTC, vatsalpatel commented on .gitignore
> +.idea/**/shelf
Don't add unnecessary changes

2023-12-04 11:35 UTC, vatsalpatel commented on maps.go
> +}
Even if it was needed, it does not follow conventions. It should be named ReverseMaps, and argument should be a slice, not variadic. It also does not belong in this file since input is a slice of maps

2023-12-04 13:54 UTC, AryanSingh11 commented
ok sir, I'll try to make some other functionalities 👍
and review the changes

2023-12-04 14:07 UTC, AryanSingh11 commented
Hi sir, pls look at  https://github.com/vatsalpatel/GoFusion/pull/7/commits/02098d2f3226a9a410e877c1ad43a53967b4d193

2023-12-04 14:08 UTC, AryanSingh11 commented
Hi sir, let me know if this is okay https://github.com/vatsalpatel/GoFusion/pull/7/commits/02098d2f3226a9a410e877c1ad43a53967b4d193

2023-12-04 14:13 UTC, AryanSingh11 reviewed
sir just added .idea, I was using Goland so .idea files also pushed from my side. That's when I though .idea files should also be included in gitignore

2023-12-05 04:35 UTC, vatsalpatel commented
This PR only adds to .gitignore so closing

2023-12-05 04:35 UTC, closed without merging

2023-12-05 13:51 UTC, AryanSingh11 commented
> This PR only adds to .gitignore so closing

is there a function you'd like me to work on?